### ISSUE TITLE
Version Block don't work

### ISSUE THREAD

**Issue by HiTimi2007** [hyperdefined/VelocityBlockVersion#18]
Hello,
The Plugin don't block the Versions... the Players can join and this come in the console:

[23:57:53 ERROR]: Couldn't pass PreLoginEvent to velocityblockversion
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.minimessage.MiniMessage net.kyori.adventure.text.minimessage.MiniMessage.get()'
        at lol.hyper.velocityblockversion.VelocityBlockVersion.onPlayerLogin(VelocityBlockVersion.java:98) ~[?:?]
        at lol.hyper.velocityblockversion.Lmbda$26.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by hyperdefined** [comment]
I had this fixed but forgot to release the update for it. I will do this shortly!

**Comment by hyperdefined** [comment]
I released the new version. Please download the use the latest version!

https://github.com/hyperdefined/VelocityBlockVersion/releases/tag/1.0.4
