### ISSUE TITLE
Plugin doesn't work on Velocity 3.2.0-SNAPSHOT

### ISSUE THREAD

**Issue by TofaDev** [hyperdefined/VelocityBlockVersion#32]
plugin version: 1.0.8

Hello, I am getting an error when trying to log in to the server. I have not changed the configuration file.

Error:
```

25.06 00:34:18.489] INFO: [Proxy-1] [00:34:18 ERROR]: Couldn't pass PreLoginEvent to velocityblockversion
[25.06 00:34:18.493] INFO: [Proxy-1] java.lang.NullPointerException: Cannot invoke "com.moandjiezana.toml.Toml.getBoolean(String, java.lang.Boolean)" because the return value of "lol.hyper.velocityblockversion.tools.ConfigHandler.getConfig()" is null       
[25.06 00:34:18.494] INFO: [Proxy-1]    at lol.hyper.velocityblockversion.events.JoinEvent.onPlayerLogin(JoinEvent.java:42) ~[?:?]
[25.06 00:34:18.496] INFO: [Proxy-1]    at lol.hyper.velocityblockversion.events.Lmbda$46.execute(Unknown Source) ~[?:?]
[25.06 00:34:18.497] INFO: [Proxy-1]    at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]                 stop                      
[25.06 00:34:18.499] INFO: [Proxy-1]    at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
[25.06 00:34:18.500] INFO: [Proxy-1]    at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]                                        stop                      
[25.06 00:34:18.507] INFO: [Proxy-1]    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
[25.06 00:34:18.509] INFO: [Proxy-1]    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
[25.06 00:34:18.510] INFO: [Proxy-1]    at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by hyperdefined** [comment]
That's an interesting one. It seems like the config failed to initialize somehow. Are there any other messages beforehand from the plugin? Try to delete the `VelocityBlockVersion` folder in your plugins folder.

**Comment by TofaDev** [comment]
there are no other errors. This error appears only when logging in to the server. I tried to delete the configuration folder, it didn't help

**Comment by hyperdefined** [comment]
Thanks for the update. That other error you posted relates to the update checker, just a 403 error. Probably rate limited from Github.

I'll look into why the join event doesn't work in a few hours when I'm available.

**Comment by hyperdefined** [comment]
https://github.com/hyperdefined/VelocityBlockVersion/releases/tag/1.0.9

Please update, as this has been fixed.
